### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [56]:
import numpy as np

In [57]:
vector = np.random.rand(10)

In [58]:
matrix = np.array([[11, 14, 17], 
              [20, 23, 26], 
              [29, 32, 35]])

In [59]:
vector.shape, vector, matrix.shape, matrix

((10,),
 array([0.17633265, 0.18544701, 0.16108846, 0.10842837, 0.180507  ,
        0.57181382, 0.23326627, 0.37619036, 0.31287778, 0.91487572]),
 (3, 3),
 array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [60]:
vector_plus_10 = (a + 10).round(2)

In [61]:
matrix_mult_2 = A * 2

In [62]:
vector_sq = a ** 2

In [63]:
vector_plus_10, matrix_mult_2, vector_sq

(array([10.19, 10.83, 10.66, 10.72, 10.22, 10.64, 10.48, 10.  , 10.76,
        10.97]),
 array([[0.36, 1.06],
        [1.5 , 0.94],
        [0.7 , 0.42]]),
 array([3.49084576e-02, 6.87564858e-01, 4.34374285e-01, 5.18486134e-01,
        4.74535521e-02, 4.09881595e-01, 2.32833260e-01, 1.38794243e-05,
        5.73296317e-01, 9.35818304e-01]))


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [64]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [65]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [66]:
result_matrix_mult_C = np.dot(result_matrix, C)
result_matrix_mult_C

array([[0.5202],
       [0.2846]])

In [67]:
result_matrix_mult_D = np.dot(result_matrix, D)
result_matrix_mult_D

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [70]:
result_matrix_T = result_matrix.T

In [92]:
vector_T = vector.T

vector, vector_T

(array([0.17633265, 0.18544701, 0.16108846, 0.10842837, 0.180507  ,
        0.57181382, 0.23326627, 0.37619036, 0.31287778, 0.91487572]),
 array([0.17633265, 0.18544701, 0.16108846, 0.10842837, 0.180507  ,
        0.57181382, 0.23326627, 0.37619036, 0.31287778, 0.91487572]))

Зміни немає.

In [93]:
vector

array([0.17633265, 0.18544701, 0.16108846, 0.10842837, 0.180507  ,
       0.57181382, 0.23326627, 0.37619036, 0.31287778, 0.91487572])

In [94]:
column_vector = np.expand_dims(vector, axis=1)

column_vector

array([[0.17633265],
       [0.18544701],
       [0.16108846],
       [0.10842837],
       [0.180507  ],
       [0.57181382],
       [0.23326627],
       [0.37619036],
       [0.31287778],
       [0.91487572]])

Операція expand_dims транспонувала(розвернула) вектор.

In [95]:
column_vector_T = column_vector.T

column_vector_T, column_vector_T.shape

(array([[0.17633265, 0.18544701, 0.16108846, 0.10842837, 0.180507  ,
         0.57181382, 0.23326627, 0.37619036, 0.31287778, 0.91487572]]),
 (1, 10))